# Generated by Django 5.2.5 on 2025-08-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_updated_at_comment_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
